# Generated by Django 5.1.6 on 2025-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_video_url_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
